/*******************************************************************************
* This file is automatically generated by PSoC Creator
* and should not be edited by hand.
*
* This file is necessary for your project to build.
* Please do not delete it.
********************************************************************************
* Copyright 2008-2011, Cypress Semiconductor Corporation.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
*******************************************************************************/
#ifndef DEVICE_H
#define DEVICE_H
#include "project.h"
#include "stmpe610.h"
#include "pff.h"
    
#define SCROLL_PER_FILE     60
#define RESOLUTION_X_PX     160 
#define RESOLUTION_X_BYTE   (RESOLUTION_X_PX / 8)
#define RESOLUTION_Y_PX     96
#define RESOLUTION_Y_BYTE   (RESOLUTION_Y_PX / 8)
    
#define constrain(amt,low,high) ((amt)<(low)?(low):((amt)>(high)?(high):(amt)))

    
uint16_t map(uint16_t x, uint16_t in_min, uint16_t in_max, uint16_t out_min, uint16_t out_max);
pos16_t map_pos(pos16_t  in, pos16_t min, pos16_t max);
void update_capsense();
FILINFO selectFile(char * dir);
void tc_callibrate(pos16_t * max, pos16_t * min);
    
#endif
/* [] END OF FILE */
